<?php

declare(strict_types=1);

namespace Waterfront\Infra\DirectAdminClient\Commands\LoginKeys;

//TODO add restriction / allowing certain CMD_* for users.
use Exception;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\Psr7\Utils;
use Psr\Http\Message\StreamInterface;
use Waterfront\Infra\DirectAdminClient\Commands\DirectAdminCommand;
use Waterfront\Infra\DirectAdminClient\Exceptions\DirectAdminResponseException;

class CreateLoginKey extends DirectAdminCommand
{
    /**
     * More information: https://www.directadmin.com/features.php?id=1298.
     *
     * @var string API Command
     */
    protected string $command = 'CMD_API_LOGIN_KEYS';

    protected string $method = 'POST';

    protected bool $useJsonResponse = false;

    protected bool $urlDecode = true;

    /**
     * This just for your own reference, and not the login username,
     * The normal User's username is still used at login time.
     *
     * @var string|null Name of the login key
     */
    private ?string $keyName = null;

    /**
     * The new secret password. Usually something long, say 128 chars.
     *
     * @var string Key to use as login
     */
    private string $key;

    /**
     * Whether the key will expire or not. If set to no, then ensure you set the expiry values.
     *
     * @var string 'yes' or 'no'
     */
    private string $neverExpires = 'yes';

    /**
     * Timestamp as to when it will expire, only used if never_expires is set to 'no'.
     * Note, you can alternatively pass the hour,minute,month,day,year values as per html form.
     *
     * @var string|null timestamp when the set key will expire.
     */
    private ?string $expiryTimestamp = null;

    /**
     * If set to >0 then this is the counter for the number of calls this key is allowed to make.
     *
     * @var int Amount of calls allowed to the API
     */
    private int $maxUses = 0;

    /**
     * If set to yes, once max_uses is hit, or expiry is hit, the key is automatically deleted.
     *
     * @var string 'yes' or 'no'
     */
    private string $clearKey = 'no';

    /**
     * If set to yes, the key can be used to acecss HTM_ CSS, and image files, etc..
     * basically things needed for browser/GUI acess, like a session login.
     * Script based CMD_API calls don't need this.
     *
     * @var string 'yes' or 'no'
     */
    private string $allowHtml = 'yes';

    /**
     * Password of the current account.
     * If using the login-as method, then it's the password used for the login-as (eg: admin's password).
     *
     * @var string password to authenticate command request.
     */
    private string $currentPassword;

    /**
     * Request a one time login url for this key.
     */
    private bool $oneTimeLogin = false;

    /**
     * The url that is send back from the DirectAdmin server
     * to use with the one time login hash.
     */
    private string $loginUrl;

    /**
     * A safe random key will be generated by default.
     *
     * @throws Exception if it was not possible to gather sufficient entropy
     */
    public function __construct()
    {
        $this->key = $this->generateSafeKey();
    }

    /**
     * Get the login url to use as a one time login.
     */
    public function getLoginUrl(): string
    {
        return $this->loginUrl;
    }

    public function doesExpire(): bool
    {
        return $this->neverExpires === 'yes';
    }

    public function getClearKey(): string
    {
        return $this->clearKey;
    }

    public function setClearKey(bool $clearKey): CreateLoginKey
    {
        $clearKey ? $this->clearKey = 'yes' : $this->clearKey = 'no';
        return $this;
    }

    public function allowHtml(): bool
    {
        return $this->allowHtml === 'yes';
    }

    public function setExpires(bool $expires = true): CreateLoginKey
    {
        $expires ? $this->neverExpires = 'no' : $this->neverExpires = 'yes';
        return $this;
    }

    public function setAllowHtml(bool $allowHtml): CreateLoginKey
    {
        $allowHtml ? $this->allowHtml = 'yes' : $this->allowHtml = 'no';
        return $this;
    }

    public function setCurrentPassword(string $currentPassword): CreateLoginKey
    {
        $this->currentPassword = $currentPassword;
        return $this;
    }

    public function isOneTimeLogin(): bool
    {
        return $this->oneTimeLogin;
    }

    public function setOneTimeLogin(bool $oneTimeLogin): CreateLoginKey
    {
        $this->oneTimeLogin = $oneTimeLogin;
        return $this;
    }

    /**
     * Check if we need to parse data after we receive a response.
     *
     *
     * @throws DirectAdminResponseException when response doesn't contain a one-time login url
     *
     */
    public function responseReceived(array $decodedContent): static
    {
        $this->setLoginUrlFromResponse($decodedContent);
        return parent::responseReceived($decodedContent);
    }

    public function getKeyName(): string
    {
        // Keyname doesn't always have to be set, a one time login URL doesn't have a keyname.
        return $this->keyName ?? '';
    }

    public function setKeyName(string $keyName): CreateLoginKey
    {
        $this->keyName = $keyName;
        return $this;
    }

    public function getKey(): string
    {
        return $this->key;
    }

    public function setKey(string $key): CreateLoginKey
    {
        $this->key = $key;
        return $this;
    }

    public function getExpiryTimestamp(): string
    {
        return $this->expiryTimestamp ?? '';
    }

    public function setExpiryTimestamp(string $expiryTimestamp): CreateLoginKey
    {
        $this->expiryTimestamp = $expiryTimestamp;
        return $this;
    }

    public function getMaxUses(): int
    {
        return $this->maxUses;
    }

    public function setMaxUses(int $maxUses): CreateLoginKey
    {
        $this->maxUses = $maxUses;
        return $this;
    }

    /**
     * Create a 'Login Keys' request to be send to the api.
     */
    protected function createRequest(): Request
    {
        return parent::createRequest()->withBody($this->getPostBody());
    }

    /**
     * Generate a random string, using a cryptographically secure
     * pseudorandom number generator (random_int).
     *
     * More info: https://stackoverflow.com/questions/4356289/php-random-string-generator/31107425#31107425
     *
     * @throws Exception if it was not possible to gather sufficient entropy
     *
     * @return string Random 64 character string
     */
    private function generateSafeKey(): string
    {
        $chars = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
        $pieces = [];
        $max = mb_strlen($chars, '8bit') - 1;
        for ($i = 0; $i < 64; ++$i) {
            $pieces[] = $chars[random_int(0, $max)];
        }

        $generated = implode('', $pieces);

        if (strlen($generated) < 40) {
            return $this->generateSafeKey();
        }

        return $generated;
    }

    /**
     * Set the login url from the response or throw an exception when the url is missing.
     *
     * @param mixed[] $response decoded response from the API
     *
     * @throws DirectAdminResponseException
     */
    private function setLoginUrlFromResponse(array $response): void
    {
        if ($this->oneTimeLogin) {
            if (array_key_exists('error', $response) && $response['error'] === '0') {
                $this->loginUrl = $response['details'];
            } else {
                throw new DirectAdminResponseException(
                    'Expected One-Time login URL to be created but received: ' . json_encode($response, JSON_THROW_ON_ERROR)
                );
            }
        }
    }

    /**
     * Get the POST data as StreamInterface for the Request body.
     */
    private function getPostBody(): StreamInterface
    {
        $params = [
            'keyname' => $this->getKeyName(),
            'key' => $this->getKey(),
            'key2' => $this->getKey(),
            'never_expires' => $this->neverExpires,
            'expiry_timestamp' => $this->getExpiryTimestamp() === '' ? $this->getExpiryTimestamp() : null,
            'max_uses' => $this->getMaxUses(),
            'clear_key' => $this->clearKey,
            'allow_html' => $this->allowHtml,
            'passwd' => $this->currentPassword,
            'action' => 'create',
            'type' => $this->oneTimeLogin ? 'one_time_url' : 'key',
            'ips' => '',
            'create' => 'Create',
        ];

        return Utils::streamFor(http_build_query($params));
    }
}
