## Create multiple custom objects and associate them with contacts
# https://developers.hubspot.com/docs/api/crm/crm-custom-objects
#
# The subscription object ID can be found in Hubspot UI
# Associations are comparable to foreign key relations, you can find the ID using the datamodel explorer
#
# Note: one error results in the whole batch failing. This behavior can be changed by implementing an objectWriteTraceId. See:
# https://developers.hubspot.com/docs/api-reference/error-handling#multi-status-errors

POST https://api.hubapi.com/crm/objects/v3/{{ subscriptionObjectTypeId }}/batch/update
Content-Type: application/json
Authorization: Bearer {{ hubspotApiKey }}

{
  "inputs": [
    {
      "id": "237684293823",
      "properties": {
          "domain": "test5.nl"
      }
    }
  ]
}
