<?php

declare(strict_types=1);

namespace Database\Seeders\Products;

enum ProductReference
{
    case ACRONIS_PROVIDER_YOURHOSTING;
    case ADD_ON_EXTRA_DB;
    case ADD_ON_EXTRA_STORAGE;
    case ADD_ON_FANCY_INSTALLER;
    case ADD_ON_EXTRA_DB_PRICE;
    case ADD_ON_EXTRA_STORAGE_PRICE;
    case ADD_ON_FANCY_INSTALLER_PRICE;
    case DOMAIN_NL;
    case DOMAIN_ADD_ON_TRUSTEE;
    case BACKUP_ACRONIS_50;
    case BACKUP_ACRONIS_100;
    case BACKUP_ACRONIS_250;
    case BACKUP_ACRONIS_500;
    case BACKUP_ACRONIS_1000;
    case BACKUP_ACRONIS_2000;
    case BACKUP_ACRONIS_50_REGISTRATION_PRICE;
    case BACKUP_ACRONIS_100_REGISTRATION_PRICE;
    case BACKUP_ACRONIS_250_REGISTRATION_PRICE;
    case BACKUP_ACRONIS_500_REGISTRATION_PRICE;
    case BACKUP_ACRONIS_1000_REGISTRATION_PRICE;
    case BACKUP_ACRONIS_2000_REGISTRATION_PRICE;
    case BASEKIT_ADD_ON_BOOKING;
    case BASEKIT_ADD_ON_BOOKING_PRICE;
    case DOMAIN_ADD_ON_TRUSTEE_PRICE;
    case DOMAIN_NL_REGISTRATION_PRICE;
    case DOMAIN_BE;
    case DOMAIN_BE_REGISTRATION_PRICE;
    case DOMAIN_COM;
    case DOMAIN_COM_REGISTRATION_PRICE;
    case DOMAIN_EU;
    case DOMAIN_EU_REGISTRATION_PRICE;
    case DOMAIN_FR;
    case DOMAIN_FR_REGISTRATION_PRICE;
    case DOMAIN_RESELLER_DISCOUNT;
    case DOMAIN_GROUP;
    case DOMAIN_PROVIDER_PLACEHOLDER;
    case DOMAIN_PROVIDER_RTR;
    case DOMAIN_PROVIDER_DEFAULT;
    case DOMAIN_PROVIDER_BUSINESS_UNIT_WATERFRONT;
    case DOMAIN_PROVIDER_BUSINESS_UNIT_ARGEWEB;

    case HOSTING_BRONZE;
    case HOSTING_BRONZE_REGISTRATION_PRICE;
    case HOSTING_BRONZE_PROLONGATION_PRICE;
    case HOSTING_SILVER;
    case HOSTING_GROOT;
    case HOSTING_MAIL_ONLY;
    case HOSTING_MAIL_ONLY_REGISTRATION_PRICE;
    case HOSTING_PREMIUM;
    case HOSTING_PREMIUM_REGISTRATION_PRICE;
    case HOSTING_WEB_BASIC;
    case HOSTING_WEB_BASIC_WP;
    case HOSTING_WEB_BASIC_REGISTRATION_PRICE;
    case HOSTING_WEB_BASIC_WP_REGISTRATION_PRICE;
    case HOSTING_WEB_ONLY_BASIC;
    case HOSTING_WEB_ONLY_BASIC_WP;
    case HOSTING_WEB_ONLY_BASIC_REGISTRATION_PRICE;
    case HOSTING_WEB_ONLY_BASIC_WP_REGISTRATION_PRICE;
    case HOSTING_WEB_ONLY_MINI;
    case HOSTING_WEB_ONLY_MINI_REGISTRATION_PRICE;
    case HOSTING_WEB_GROW;
    case HOSTING_WEB_GROW_WP;
    case HOSTING_WEB_GROW_REGISTRATION_PRICE;

    case HOSTING_WEB_ONLY_GROW;
    case HOSTING_WEB_ONLY_GROW_WP;
    case HOSTING_WEB_ONLY_GROW_REGISTRATION_PRICE;

    case HOSTING_WEB_ONLY_START;
    case HOSTING_WEB_ONLY_START_WP;
    case HOSTING_WEB_ONLY_START_REGISTRATION_PRICE;

    case HOSTING_WEB_ONLY_PLUS;
    case HOSTING_WEB_ONLY_PLUS_WP;
    case HOSTING_WEB_ONLY_PLUS_REGISTRATION_PRICE;
    case HOSTING_PLACEHOLDER;
    case HOSTING_PLACEHOLDER_REGISTRATION_PRICE;
    case HOSTING_PROVISIONING;
    case HOSTING_PROVISIONING_REGISTRATION_PRICE;
    case HOSTING_WEB_START;
    case HOSTING_WEB_START_WP;
    case HOSTING_WEB_START_REGISTRATION_PRICE;
    case HOSTING_WEB_PLUS;
    case HOSTING_WEB_PLUS_WP;
    case HOSTING_WEB_PLUS_REGISTRATION_PRICE;
    case HOSTING_MAIL_ONLY_BASIC_DIRECT_ADMIN;
    case HOSTING_MAIL_ONLY_BASIC_DIRECT_ADMIN_REGISTRATION_PRICE;
    case HOSTING_MAIL_ONLY_BASIC_DIRECT_ADMIN_PROLONGATION_PRICE;
    case HOSTING_MAIL_ONLY_GROW_PLESK;
    case HOSTING_MAIL_ONLY_GROW_PLESK_REGISTRATION_PRICE;
    case HOSTING_MAIL_ONLY_START_PLESK;
    case HOSTING_MAIL_ONLY_START_PLESK_REGISTRATION_PRICE;
    case HOSTING_MAIL_ONLY_PLUS_PLESK;
    case HOSTING_MAIL_ONLY_PLUS_PLESK_REGISTRATION_PRICE;
    case HOSTING_WORDPRESS_TOOLKIT;
    case HOSTING_WORDPRESS_TOOLKIT_REGISTRATION_PRICE;
    case HOSTING_GROUP;
    case HOSTING_PROVIDER_DIRECT_ADMIN;
    case HOSTING_PROVIDER_PLACEHOLDER;
    case HOSTING_PROVIDER_PLESK;
    case HOSTING_PROVIDER_MAIL_ONLY_PLESK;
    case HOSTING_PROVIDER_DEFAULT;
    case HOSTING_MAIL_ONLY_PROVIDER_DIRECT_ADMIN;
    case HOSTING_MAIL_ONLY_PROVIDER_PLACEHOLDER;
    case HOSTING_MAIL_ONLY_SERVER_DIRECT_ADMIN;
    case HOSTING_SERVER_PLESK;
    case HOSTING_SERVER_DIRECT_ADMIN;
    case SERVICE_SERVICE_PLUS;
    case SERVICE_SERVICE_PLUS_REGISTRATION_PRICE;
    case MICROSOFT_APPS_FOR_BUSINESS_CHILD;
    case MICROSOFT_APPS_FOR_BUSINESS_CHILD_REGISTRATION_PRICE_MONTH;
    case MICROSOFT_APPS_FOR_BUSINESS_CHILD_REGISTRATION_PRICE_YEAR;
    case MICROSOFT_APPS_FOR_BUSINESS_PARENT;
    case MICROSOFT_APPS_FOR_BUSINESS_PARENT_REGISTRATION_PRICE_MONTH;
    case MICROSOFT_APPS_FOR_BUSINESS_PARENT_REGISTRATION_PRICE_YEAR;

    case SITEBUILDER_PROVIDER;
    case SITEBUILDER_PROVIDER_PLACEHOLDER;
    case SITEBUILDER_SERVER;
    case SITEBUILDER_BASEKIT;
    case SITEBUILDER_SHOP_BASEKIT;
    case SITEBUILDER_BASEKIT_REGISTRATION_PRICE;
    case SITEBUILDER_SHOP_BASEKIT_REGISTRATION_PRICE;

    case SSL_SINGLE_DOMAIN;
    case SSL_SINGLE_DOMAIN_PROLONGATION_PRICE;
    case SSL_PROVIDER_PLACEHOLDER;
    case DNS_FREE;
    case DNS_FREE_REGISTRATION_PRICE;
    case DNS_PREMIUM;
    case DNS_PREMIUM_REGISTRATION_PRICE;
    case DNS_VANITY_NAMESERVER_1;
    case DNS_VANITY_NAMESERVER_2;
    case DNS_VANITY_NAMESERVER_3;
    case DNS_NAMESERVER_1;
    case DNS_NAMESERVER_2;
    case DNS_NAMESERVER_3;

    case RESELLER_HOSTING_GROUP;
    case RESELLER_HOSTING_BRONS;
    case RESELLER_HOSTING_BRONS_REGISTRATION_PRICE;
    case RESELLER_HOSTING_BRONS_PROLONGATION_PRICE;
    case RESELLER_HOSTING_SILVER;
    case RESELLER_HOSTING_SILVER_REGISTRATION_PRICE;
    case RESELLER_HOSTING_GOLD;
    case RESELLER_HOSTING_GOLD_REGISTRATION_PRICE;

    case SSL_WILDCARD;
    case SSL_WILDCARD_REGISTRATION_PRICE;
    case SSL_SINGLE_DOMAIN_REGISTRATION_PRICE;
    case SSL_PLACEHOLDER;
    case SSL_PLACEHOLDER_REGISTRATION_PRICE;
    case SSL_EXTENDED_VALIDATION;
    case SSL_EXTENDED_VALIDATION_REGISTRATION_PRICE;
    case SSL_PROVIDER_RTR;

    case VPS_GROUP;
    case VPS_GROUP_OS;
    case VPS_ENVIRONMENT_HAARLEM;
    case VPS_ENVIRONMENT_AMSTERDAM;
    case VPS_OS_UBUNTU;
    case VPS_OS_UBUNTU_SSH_REQUIRED;
    case VPS_OS_UBUNTU_REGISTRATION_PRICE;
    case VPS_CLOUD_2;
    case VPS_CLOUD_2_REGISTRATION_PRICE;
    case VPS_CLOUD_5;
    case VPS_CLOUD_5_REGISTRATION_PRICE;
    case VPS_CLOUD_10;
    case VPS_CLOUD_10_REGISTRATION_PRICE;
    case VPS_CLOUD_20;
    case VPS_CLOUD_20_REGISTRATION_PRICE;
    case VPS_CLOUD_20_VOUCHER;

    case VOLUME_DISCOUNT_BRONS;
    case VOLUME_DISCOUNT_BRONS_REGISTRATION_PRICE;
    case VOLUME_DISCOUNT_HOSTING_BRONS_PRODUCT_DISCOUNT;
    case VOLUME_DISCOUNT_HOSTING_BRONS_PRODUCT_DISCOUNT_REGISTRATION_PRICE;

    case ONE_TIME_SERVICE_WORDPRESS_DESIGN;
    case ONE_TIME_SERVICE_WORDPRESS_DESIGN_PRICE;

    case REDIRECT_PAID_REDIRECT;
    case REDIRECT_CADDY_REDIRECT;
    case REDIRECT_REGISTRATION_PRICE;
}
