<?php

declare(strict_types=1);

namespace Database\Seeders\Scenarios;

enum ScenarioReference
{
    case TEST_KEES;
    case TEST_KEES_ORDER;
    case MIGRATION_CUSTOMER;
    case TEST_KEES_DOMAIN_NL_SUBSCRIPTION;
    case TEST_KEES_DOMAIN_NL_SUBSCRIPTION_EXTERNAL_NAMESERVERS;
    case TEST_KEES_DOMAIN_EU_SUBSCRIPTION;
    case TEST_KEES_DOMAIN_BE_SUBSCRIPTION;
    case TEST_KEES_DOMAIN_COM_SUBSCRIPTION;
    case TEST_KEES_DOMAIN_CONTACT;
    case REGULAR_CUSTOMER;
    case M365_CUSTOMER_INFO;
    case M365_DEPLOYMENT;
    case VOUCHER_CUSTOMER;
    case DISCOUNT_KEES;
    case TEST_KEES_VPS_MANAGER_DOMAIN_DEPLOYMENT_HAARLEM;
    case TEST_KEES_VPS_MANAGER_DOMAIN_DEPLOYMENT_AMSTERDAM;
    case TEST_KEES_PUZZEL_FIRST_CALLBACK_TIMESLOT;
}
