<?php

declare(strict_types=1);

namespace Waterfront\Infra\RtrClient\Services\Enums;

// See: https://dm.realtimeregister.com/docs/api/domains/update
enum DomainStatus: string
{
    case OK = 'OK';
    case INACTIVE = 'INACTIVE';
    case PENDING_TRANSFER = 'PENDING_TRANSFER';
    case PENDING_RENEW = 'PENDING_RENEW';
    case PENDING_UPDATE = 'PENDING_UPDATE';
    case DELETE_REQUESTED = 'DELETE_REQUESTED';
    case PENDING_DELETE = 'PENDING_DELETE';
    case ADD_PERIOD = 'ADD_PERIOD';
    case RENEW_PERIOD = 'RENEW_PERIOD';
    case AUTO_RENEW_PERIOD = 'AUTO_RENEW_PERIOD';
    case TRANSFER_PERIOD = 'TRANSFER_PERIOD';
    case REDEMPTION_PERIOD = 'REDEMPTION_PERIOD';
    case PENDING_RESTORE = 'PENDING_RESTORE';
    case CLIENT_HOLD = 'CLIENT_HOLD';
    case CLIENT_DELETE_PROHIBITED = 'CLIENT_DELETE_PROHIBITED';
    case CLIENT_UPDATE_PROHIBITED = 'CLIENT_UPDATE_PROHIBITED';
    case CLIENT_RENEW_PROHIBITED = 'CLIENT_RENEW_PROHIBITED';
    case CLIENT_TRANSFER_PROHIBITED = 'CLIENT_TRANSFER_PROHIBITED';
    case REGISTRAR_HOLD = 'REGISTRAR_HOLD';
    case REGISTRAR_DELETE_PROHIBITED = 'REGISTRAR_DELETE_PROHIBITED';
    case REGISTRAR_UPDATE_PROHIBITED = 'REGISTRAR_UPDATE_PROHIBITED';
    case REGISTRAR_RENEW_PROHIBITED = 'REGISTRAR_RENEW_PROHIBITED';
    case REGISTRAR_TRANSFER_PROHIBITED = 'REGISTRAR_TRANSFER_PROHIBITED';
    case SERVER_HOLD = 'SERVER_HOLD';
    case SERVER_DELETE_PROHIBITED = 'SERVER_DELETE_PROHIBITED';
    case SERVER_UPDATE_PROHIBITED = 'SERVER_UPDATE_PROHIBITED';
    case SERVER_RENEW_PROHIBITED = 'SERVER_RENEW_PROHIBITED';
    case SERVER_TRANSFER_PROHIBITED = 'SERVER_TRANSFER_PROHIBITED';
    case PENDING_VALIDATION = 'PENDING_VALIDATION';
    case PRIVACY_PROTECT_PROHIBITED = 'PRIVACY_PROTECT_PROHIBITED';
    case EXPIRED = 'EXPIRED';
    case IRTPC_TRANSFER_PROHIBITED = 'IRTPC_TRANSFER_PROHIBITED';
}
